"""HTTP cache helpers — ``Cache-Control`` policy for the read-only API.

The dataset is regenerated by the pipeline at most once a day, so most
responses are very cacheable. Each route opts in via the
``dependencies=[...]`` argument on its decorator:

>>> @router.get("", dependencies=[CACHE_DAY])
... async def list_observances(...): ...

The dependency receives the ASGI ``Response`` and stamps a ``Cache-Control``
header — the route handler stays clean and never has to think about HTTP
caching plumbing. Policies that depend on wall-clock time (e.g. "expire at
the next UTC midnight") accept a callable so they're re-evaluated per
request.

We deliberately don't ship ``ETag`` for v1 — the wins from
revalidation-by-hash on a sub-kilobyte JSON body are marginal compared to
the simpler "max-age until tomorrow" model below, and ETag adds a per-
request body hash that's wasted CPU under cache-hit traffic anyway.
"""

from collections.abc import Callable
from datetime import UTC, datetime, timedelta

from fastapi import Depends, Response

# ---------------------------------------------------------------------------
# Static policies. ``s-maxage`` lets a CDN keep a longer copy than the
# browser, which is what we want — the browser refreshes after one day,
# the CDN holds for a week.
# ---------------------------------------------------------------------------
_DAY = "public, max-age=86400, s-maxage=604800"
_HOUR = "public, max-age=3600, s-maxage=86400"
_FIVE_MIN = "public, max-age=300, s-maxage=900"
_NO_STORE = "no-store"


def _cache_until_utc_midnight() -> str:
    """``Cache-Control`` value that expires at the next UTC midnight.

    Today / Recent pivot at midnight UTC — the headline, secondary rails,
    and observance can all flip. Setting ``max-age`` to "seconds until
    next 00:00 UTC" means the browser caches the current day's payload
    aggressively but never serves yesterday's content past the rollover.
    """
    now = datetime.now(UTC)
    tomorrow = (now + timedelta(days=1)).replace(hour=0, minute=0, second=0, microsecond=0)
    seconds = max(60, int((tomorrow - now).total_seconds()))
    return f"public, max-age={seconds}, s-maxage={seconds}"


def _cache_dependency(policy: str | Callable[[], str]):
    """Build a FastAPI dependency that stamps a ``Cache-Control`` header.

    Args:
        policy: Either a literal ``Cache-Control`` value, or a zero-arg
            callable that returns one (re-evaluated per request — used for
            "max-age until next midnight" so each response advertises a
            forward-looking expiry).

    Returns:
        A ``Depends(...)`` instance to drop into a route's
        ``dependencies=[...]`` list.
    """

    def _set(response: Response) -> None:
        response.headers["Cache-Control"] = policy() if callable(policy) else policy

    return Depends(_set)


# ---------------------------------------------------------------------------
# Public dependencies. Drop into ``dependencies=[...]`` on a route.
# ---------------------------------------------------------------------------
CACHE_UNTIL_MIDNIGHT = _cache_dependency(_cache_until_utc_midnight)
CACHE_DAY = _cache_dependency(_DAY)
CACHE_HOUR = _cache_dependency(_HOUR)
CACHE_FIVE_MIN = _cache_dependency(_FIVE_MIN)
NO_STORE = _cache_dependency(_NO_STORE)
