/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SavesRouteImport } from './routes/saves'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecentRouteImport } from './routes/recent'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObservancesIndexRouteImport } from './routes/observances.index'
import { Route as PeopleSlugRouteImport } from './routes/people.$slug'
import { Route as ObservancesSlugRouteImport } from './routes/observances.$slug'
import { Route as LessonsSlugRouteImport } from './routes/lessons.$slug'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SavesRoute = SavesRouteImport.update({
  id: '/saves',
  path: '/saves',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentRoute = RecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservancesIndexRoute = ObservancesIndexRouteImport.update({
  id: '/observances/',
  path: '/observances/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleSlugRoute = PeopleSlugRouteImport.update({
  id: '/people/$slug',
  path: '/people/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservancesSlugRoute = ObservancesSlugRouteImport.update({
  id: '/observances/$slug',
  path: '/observances/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsSlugRoute = LessonsSlugRouteImport.update({
  id: '/lessons/$slug',
  path: '/lessons/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/recent': typeof RecentRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saves': typeof SavesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/events/$slug': typeof EventsSlugRoute
  '/lessons/$slug': typeof LessonsSlugRoute
  '/observances/$slug': typeof ObservancesSlugRoute
  '/people/$slug': typeof PeopleSlugRoute
  '/observances/': typeof ObservancesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/recent': typeof RecentRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saves': typeof SavesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/events/$slug': typeof EventsSlugRoute
  '/lessons/$slug': typeof LessonsSlugRoute
  '/observances/$slug': typeof ObservancesSlugRoute
  '/people/$slug': typeof PeopleSlugRoute
  '/observances': typeof ObservancesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/recent': typeof RecentRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saves': typeof SavesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/events/$slug': typeof EventsSlugRoute
  '/lessons/$slug': typeof LessonsSlugRoute
  '/observances/$slug': typeof ObservancesSlugRoute
  '/people/$slug': typeof PeopleSlugRoute
  '/observances/': typeof ObservancesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/recent'
    | '/reset-password'
    | '/saves'
    | '/sign-in'
    | '/sign-up'
    | '/events/$slug'
    | '/lessons/$slug'
    | '/observances/$slug'
    | '/people/$slug'
    | '/observances/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/recent'
    | '/reset-password'
    | '/saves'
    | '/sign-in'
    | '/sign-up'
    | '/events/$slug'
    | '/lessons/$slug'
    | '/observances/$slug'
    | '/people/$slug'
    | '/observances'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/recent'
    | '/reset-password'
    | '/saves'
    | '/sign-in'
    | '/sign-up'
    | '/events/$slug'
    | '/lessons/$slug'
    | '/observances/$slug'
    | '/people/$slug'
    | '/observances/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  RecentRoute: typeof RecentRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SavesRoute: typeof SavesRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  EventsSlugRoute: typeof EventsSlugRoute
  LessonsSlugRoute: typeof LessonsSlugRoute
  ObservancesSlugRoute: typeof ObservancesSlugRoute
  PeopleSlugRoute: typeof PeopleSlugRoute
  ObservancesIndexRoute: typeof ObservancesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saves': {
      id: '/saves'
      path: '/saves'
      fullPath: '/saves'
      preLoaderRoute: typeof SavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent': {
      id: '/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof RecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observances/': {
      id: '/observances/'
      path: '/observances'
      fullPath: '/observances/'
      preLoaderRoute: typeof ObservancesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$slug': {
      id: '/people/$slug'
      path: '/people/$slug'
      fullPath: '/people/$slug'
      preLoaderRoute: typeof PeopleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observances/$slug': {
      id: '/observances/$slug'
      path: '/observances/$slug'
      fullPath: '/observances/$slug'
      preLoaderRoute: typeof ObservancesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$slug': {
      id: '/lessons/$slug'
      path: '/lessons/$slug'
      fullPath: '/lessons/$slug'
      preLoaderRoute: typeof LessonsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  RecentRoute: RecentRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SavesRoute: SavesRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  EventsSlugRoute: EventsSlugRoute,
  LessonsSlugRoute: LessonsSlugRoute,
  ObservancesSlugRoute: ObservancesSlugRoute,
  PeopleSlugRoute: PeopleSlugRoute,
  ObservancesIndexRoute: ObservancesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
