/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RecentRouteImport } from './routes/recent'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObservancesIndexRouteImport } from './routes/observances.index'
import { Route as PeopleSlugRouteImport } from './routes/people.$slug'
import { Route as ObservancesSlugRouteImport } from './routes/observances.$slug'
import { Route as LessonsSlugRouteImport } from './routes/lessons.$slug'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentRoute = RecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservancesIndexRoute = ObservancesIndexRouteImport.update({
  id: '/observances/',
  path: '/observances/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleSlugRoute = PeopleSlugRouteImport.update({
  id: '/people/$slug',
  path: '/people/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservancesSlugRoute = ObservancesSlugRouteImport.update({
  id: '/observances/$slug',
  path: '/observances/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsSlugRoute = LessonsSlugRouteImport.update({
  id: '/lessons/$slug',
  path: '/lessons/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/recent': typeof RecentRoute
  '/search': typeof SearchRoute
  '/events/$slug': typeof EventsSlugRoute
  '/lessons/$slug': typeof LessonsSlugRoute
  '/observances/$slug': typeof ObservancesSlugRoute
  '/people/$slug': typeof PeopleSlugRoute
  '/observances/': typeof ObservancesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/recent': typeof RecentRoute
  '/search': typeof SearchRoute
  '/events/$slug': typeof EventsSlugRoute
  '/lessons/$slug': typeof LessonsSlugRoute
  '/observances/$slug': typeof ObservancesSlugRoute
  '/people/$slug': typeof PeopleSlugRoute
  '/observances': typeof ObservancesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/recent': typeof RecentRoute
  '/search': typeof SearchRoute
  '/events/$slug': typeof EventsSlugRoute
  '/lessons/$slug': typeof LessonsSlugRoute
  '/observances/$slug': typeof ObservancesSlugRoute
  '/people/$slug': typeof PeopleSlugRoute
  '/observances/': typeof ObservancesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/recent'
    | '/search'
    | '/events/$slug'
    | '/lessons/$slug'
    | '/observances/$slug'
    | '/people/$slug'
    | '/observances/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/recent'
    | '/search'
    | '/events/$slug'
    | '/lessons/$slug'
    | '/observances/$slug'
    | '/people/$slug'
    | '/observances'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/recent'
    | '/search'
    | '/events/$slug'
    | '/lessons/$slug'
    | '/observances/$slug'
    | '/people/$slug'
    | '/observances/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  RecentRoute: typeof RecentRoute
  SearchRoute: typeof SearchRoute
  EventsSlugRoute: typeof EventsSlugRoute
  LessonsSlugRoute: typeof LessonsSlugRoute
  ObservancesSlugRoute: typeof ObservancesSlugRoute
  PeopleSlugRoute: typeof PeopleSlugRoute
  ObservancesIndexRoute: typeof ObservancesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent': {
      id: '/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof RecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observances/': {
      id: '/observances/'
      path: '/observances'
      fullPath: '/observances/'
      preLoaderRoute: typeof ObservancesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$slug': {
      id: '/people/$slug'
      path: '/people/$slug'
      fullPath: '/people/$slug'
      preLoaderRoute: typeof PeopleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observances/$slug': {
      id: '/observances/$slug'
      path: '/observances/$slug'
      fullPath: '/observances/$slug'
      preLoaderRoute: typeof ObservancesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$slug': {
      id: '/lessons/$slug'
      path: '/lessons/$slug'
      fullPath: '/lessons/$slug'
      preLoaderRoute: typeof LessonsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  RecentRoute: RecentRoute,
  SearchRoute: SearchRoute,
  EventsSlugRoute: EventsSlugRoute,
  LessonsSlugRoute: LessonsSlugRoute,
  ObservancesSlugRoute: ObservancesSlugRoute,
  PeopleSlugRoute: PeopleSlugRoute,
  ObservancesIndexRoute: ObservancesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
